config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  resources :questions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :question, presence: true
  validates :description, presence: true
  has_many :question_similar_words, dependent: :destroy
  accepts_nested_attributes_for :question_similar_words, reject_if: :all_blank,allow_destroy: true

  class << self
    def search(search)
      if search
        Question.where(['question LIKE ? OR description LIKE ?', "%#{search}%", "%#{search}%"])
      else
        Question.all
      end
    end
  end
end

app/models/question_similar_word.rb
class QuestionSimilarWord < ApplicationRecord
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 20}, uniqueness: true
  validates :password, presence: true, length: {minimum: 4}, allow_nil: true
  has_secure_password
  default_scope -> {order(highest_score: :desc)}

  # def current_user?
  #   self.id == session[:user_id]
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  def logged_in_user
    redirect_to login_path unless logged_in?
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :logged_in_user
  before_action :find_question, only: [:edit, :update, :destroy]

  def index
    @questions = Question.search(params[:search])
  end

  def show
    if session[:correct].to_i + session[:incorrect].to_i < 9 || params[:question_id].nil?
      if params[:question_id]
        last_question = Question.find(params[:question_id])
        user_answer = Question.find(params[:question])
        if user_answer.description == last_question.description
          # flash.now[:success] = "正解です。"
          session[:correct] += 1
        else
          # flash.now[:danger] = "不正解です。 正解：#{last_question.description}"
          session[:incorrect] += 1
        end
      else
        session[:correct] = 0
        session[:incorrect] = 0
      end
      # rand_number = Question.all.map(&:id).sample
      # @question = Question.find(rand_number)
      if session[:correct] == 0 && session[:incorrect] == 0
        $wordtests = Question.all.sample(10)
        if $wordtests.size <10
          flash[:danger] = "現在の単語数は#{Question.all.count}個です。問題を10問以上作成してください"
          redirect_to new_question_path
        end
        if QuestionSimilarWord
          nums = QuestionSimilarWord.all.map(&:question_id)
          most_having_similar_id = nums.max_by {|x| nums.count(x)}
          $most_similar_number = Question.find(most_having_similar_id).question_similar_words.count
        end
      end
      @question = $wordtests.shift
      if @question
        @similar_words = @question.question_similar_words
        @questions = (Question.where.not(id: @question.id).sample(2) << @question).shuffle
      else
        render :js => "window.location = '#{root_path}'"
      end
      respond_to do |format|
        format.html
        format.js
      end
    else
      last_question = Question.find(params[:question_id])
      user_answer = Question.find(params[:question])
      if user_answer.description == last_question.description
        session[:correct] += 1
      else
        session[:incorrect] += 1
      end
      render :js => "window.location = '#{users_path}'"
    end
  end

  def new
    @question = Question.new
    @question_similar_word = @question.question_similar_words.build
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      flash[:success] = "単語の登録に成功しました"
      redirect_to questions_path
    else
      render 'new'
    end
  end

  def edit
    @question_similar_word = @question.question_similar_words.new
  end

  def update
    if @question.update_attributes(question_params)
      flash[:success] = "単語編集が完了しました。"
      redirect_to questions_path
    else
      render 'edit'
    end
  end

  def destroy
    @question.destroy
    flash[:success] = "単語を削除しました"
    redirect_to questions_path
  end

  private

    def question_params
      params.require(:question).permit(:question, :description,
        question_similar_words_attributes:[:id, :similar_word, :_destroy])
    end

    def find_question
      @question = Question.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user && user.authenticate(params[:password])
      flash[:success] = "ログインに成功しました。"
      log_in user
      redirect_to root_url
    else
      flash.now[:danger] = "ユーザ名又はパスワードが違います"
      render 'new'
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    unless Question.count == 0
      rand_number = Question.all.map(&:id).sample
      @question = Question.find(rand_number)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "ユーザー登録に成功しました"
      log_in @user
      redirect_to root_path
    else
      render 'new'
    end
  end

  def index
    @users = User.all
    unless session[:correct].nil? || session[:incorrect].nil? || (session[:correct] == 0 && session[:incorrect] == 0) || session[:correct] + session[:incorrect] < 10
      correct_answer_late = session[:correct]*100 / (session[:correct].to_i + session[:incorrect].to_i)
      scores = @users.map(&:highest_score)
      scores << correct_answer_late
      scores.sort!.reverse!
      flash.now[:success] = "お疲れ様でした！あなたの成績は、#{session[:correct].to_i + session[:incorrect].to_i}問中、#{session[:correct].to_i}問正解。正解率#{correct_answer_late}%で#{scores.index(correct_answer_late) + 1}位でした"
      session[:correct] = 0
      session[:incorrect] = 0
      if current_user.highest_score <= correct_answer_late
        current_user.update_attribute(:highest_score, correct_answer_late)
      end
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_similar_words_helper.rb
module QuestionSimilarWordsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user = @current_user || User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WordTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |message_type, msg|%>
        <div class = "alert alert-<%= message_type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
      <% if Rails.env.development? %>
        <%= debug(params) %>
        <p id = "session-correct"><%= "session[:correct]: #{session[:correct]}" %></p>
        <p id = "session-incorrect"><%= "session[:incorrect]: #{session[:incorrect]}" %></p>
      <% end %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: @question, local: true do |f|%>
  <p><%= render "shared/error_messages", object: f.object %></p>

  <p><%= f.label :question, "英単語" %></p>
  <p><%= f.text_field :question, class: 'form-control'  %></p>

  <p><%= f.label :description, "英単語の答え、説明" %></p>
  <p><%= f.text_field :description, class: 'form-control'  %></p>

  <hr>
  <div class = "similar_words">
    <p> 類似単語　</p>
    <%= f.fields_for :question_similar_words do |q| %>
      <%= render 'question_similar_word_fields', f: q %>
    <% end %>
    <div class ="links">
      <p><%= link_to_add_association '類似単語を追加', f, :question_similar_words, class: "btn btn-info" %></p>
    </div>
  </div>
  <hr>

  <p><%= f.submit "単語を登録", class: "btn btn-primary" %></p>
<% end %>

app/views/questions/_question.html.erb
<div class = "row">
  <div class = "col-xs-6">
    <p><%= question.question %></p>
    <p><%= question.description %></p>
    <h5>
      <%= link_to "編集 |", edit_question_path(question) %>
      <%= link_to "削除", question, method: :delete, data: {confirm:"本当に削除しますか？"} %>
    </h5>
  </div>
  <div class = "col-xs-6">
    <p>類似単語</p>
    <% if question.question_similar_words.any? %>
    <% question.question_similar_words.each do |word| %>
      <ul>
        <li class= "similar-word">
          <%= word.similar_word %>
        </li>
      </ul>
    <% end %>
    <% else %>
     <p> <%= link_to "未登録です", edit_question_path(question) %></p>
    <% end %>
  </div>
</div>
<hr>

app/views/questions/_question_similar_word_fields.html.erb
<div class = "nested-fields">
  <div class="row">
    <div class = "col-xs-9">
      <p><%= f.text_field :similar_word %></p>
    </div>
    <div class = "col-xs-3">
      <p><%= link_to_remove_association "削除", f, class: "btn btn-info"%></p>
    </div>
  </div>
</div>

app/views/questions/edit.html.erb
<div class = "row">
  <div class = "col-md-6 col-md-offset-3">
    <div class = "panel panel-primary">
      <div class = "panel-heading">
        <h1>英単語編集</h1>
      </div>
      <div class = "panel-body">
        <%= render "form" %>
        <hr>
        <p><%= link_to "マスタメンテナンスに戻る", questions_path %></p>
      </div>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<div class = "row">
  <div class = "col-md-8 col-md-offset-2">
    <div class = "panel panel-primary">
      <div class = "panel-heading">
        <h1>単語マスタメンテナンス</h1>
      </div>
      <div class = "panel-body">
        <ul>
        <li><%= link_to "単語新規作成", new_question_path %></li>
        <li><%= link_to "メインメニューに戻る", root_path %></li>
        </ul>
        <div class = "row search-form">
          <%= form_with url: questions_path, method: 'get', local:true do |f| %>
            <div class = "col-xs-9">
              <%= f.text_field :search,  class: "form-control" %>
            </div>
            <div class = "col-xs-3">
              <%= f.submit "検索", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
        <hr>
        <% if @questions %>
          <%= render @questions %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class = "row">
  <div class = "col-md-6 col-md-offset-3">
    <div class = "panel panel-primary">
      <div class = "panel-heading">
        <h1>新規英単語登録</h1>
      </div>
      <div class = "panel-body">
        <%= render 'form' %>
        <hr>
        <p><%= link_to "マスタメンテナンスに戻る", questions_path %></p>
      </div>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<div class = "row">
  <div class = "col-md-6 col-md-offset-3">
    <div class = "panel panel-primary">
      <div class = "panel-heading">
        <h1>単語帳</h1>
      </div>
      <div class = "panel-body">
        <p id="question_number">第<%= session[:correct] + session[:incorrect] + 1 %>問</p>
        <hr>
        <h1 id="question_question"><%= @question.question %></h1>

        <div class = "similar-words">
        <% if @similar_words.present? %>
          <p>類似単語</p>
          <% @similar_words.each_with_index do |word, n| %>
            <p id = "similar_word<%= n %>"><%= word.similar_word %></p>
          <% end %>
        <% else %>
          <% $most_similar_number.times do |m| %>
            <p id = "similar_word<%= m %>"></p>
          <% end %>
        <% end %>
        </div>
        <hr>

        <%= form_with url: question_path, method: "get" do |f|%>

          <%= f.hidden_field :question_id, value: @question.id %>
          <div class="radio-button">
            <% @questions.each_with_index do |question, i| %>
              <p id="question_answer<%= i %>">
                <% if i == 0 %>
                  <%= radio_button_tag :question, question.id, checked: "checked"%>
                  <%= label_tag "question_#{question.id}", question.description %>
                <% else %>
                  <%= radio_button_tag :question, question.id %>
                  <%= label_tag "question_#{question.id}", question.description %>
                <% end %>
              </p>
            <% end %>
          </div>

          <p><%= f.submit "解答", class: "btn btn-primary" %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/questions/show.js.erb
$("#question_number").html('第<%= session[:correct] + session[:incorrect] + 1 %>問');
$("#question_question").html('<%= @question.question %>');
//$("#question_answer0").html('<%= radio_button_tag :question, answer_id=@questions.shift.id, checked: "checked"%>\n' +
//    '            <%= label_tag "question_#{answer_id}", Question.find(answer_id).description %>');
//$("#question_answer1").html('<%= radio_button_tag :question, answer_id=@questions.shift.id%>\n' +
//    '            <%= label_tag "question_#{answer_id}", Question.find(answer_id).description %>');
//$("#question_answer2").html('<%= radio_button_tag :question, answer_id=@questions.shift.id%>\n' +
//    '            <%= label_tag "question_#{answer_id}", Question.find(answer_id).description %>');
<% @questions.shuffle.each_with_index do |question, i| %>
 var target_dom = $("#question_answer<%= i %>");
 var radio_btn  = target_dom.children("input")[0];
 radio_btn.id   = "question_<%= question.id %>";
 radio_btn.value = "<%= question.id  %>";
 <% if i.zero? %>
    radio_btn.checked = true
 <% else %>
    radio_btn.checked = false
 <%end %>

  var label = target_dom.children("label")[0];
  label.attributes[0].nodeValue = "question_<%= question.id %>";
  label.innerHTML  = "<%= question.description %>";
<% end %>
$("#session-correct").html("session[:correct]: <%= session[:correct] %>");
$("#session-incorrect").html("session[:incorrect]: <%= session[:incorrect] %>");
<%  p @question.id %>
//$("#question_id").html('<input value="<%#= @question.id %>" type="hidden" name="question_id"/>')
// $("#question_id").html('<%#= hidden_field_tag :question_id, @question.id %>')
$("#question_id")[0].value = '<%= @question.id %>';
document.getElementById("question_id");
<% if @similar_words.present? %>
  <% @similar_words.each_with_index do |word, n| %>
  $("#similar_word<%= n %>").html('<%= word.similar_word %>');
  <% end %>
<% else %>
  $(".similar-words").html('<% $most_similar_number.times do |m| %>\n' +
      '            <p id = "similar_word<%= m %>"></p>\n' +
      '          <% end %>');
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
 <ul>
   <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
   <% end %>
 </ul>
<% end %>

app/views/static_pages/home.html.erb
<div class = "row">
  <div class = "col-md-8 col-md-offset-2">
    <div class = "panel panel-primary">
      <div class = "panel-heading">
        <h1>Main menu</h1>
      </div>
      <div class = "panel-body">
        <p>下記のメニューよりクリックしてください</p>
        <ul>
        <li><%= link_to "新規ユーザ作成", new_user_path %></li>
        <% unless Question.count == 0 %>
          <li><%= link_to "単語帳", question_path(@question) %></li>
        <% else %>
          <li>単語帳</li>
        <% end %>
        <li><%= link_to "ランキング", users_path %></li>
        <li><%= link_to "単語マスタメンテナンス", questions_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class = "row">
  <div class = "col-md-8 col-md-offset-2">
    <div class = "panel panel-primary">
      <div class = "panel-heading">
        <h1 id = "ranking">ランキング</h1>
      </div>
      <div class = "panel-body">
        <% @users.each_with_index do |user,i| %>
          <div id = <%= "current_user" if user.id == session[:user_id] %>>
            <h2>第<%= i + 1 %>位　<%= user.name %></h2>
            <h3>正答率：　<%= user.highest_score %></h3>
          </div>
          <hr>
        <% end %>
        <p><%= link_to "メインメニューに戻る", root_path %><p>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class = "row">
  <div class = "col-md-6 col-md-offset-3">
    <div class = "panel panel-primary">
      <div class = "panel-heading">
        <h1>新規ユーザー登録</h1>
      </div>
      <div class = "panel-body">
        <%= form_with model: @user, local: true do |f|%>
          <p><%= render "shared/error_messages", object: f.object %></p>

          <p><%= f.label :name, "ユーザーネーム" %></p>
          <p><%= f.text_field :name, class: 'form-control'  %></p>

          <p><%= f.label :password, "パスワード（４文字以上）" %></p>
          <p><%= f.password_field :password, class: 'form-control'  %></p>

          <p><%= f.label :password_confirmation, "パスワード確認" %></p>
          <p><%= f.password_field :password_confirmation, class: 'form-control'  %></p>

          <p><%= f.submit "ユーザーを登録する", class: "btn btn-primary" %></p>
        <% end %>
      </div>
    </div>
    <p>すでに登録してる方はこちら｜<%= link_to "ログイン", login_path %></p>
  </div>
</div>